### ISSUE TITLE
easier installation / integration into scverse

### ISSUE THREAD

**Issue by esrice** [mossjacob/pyslingshot#12]
Hi! Thanks for porting slingshot to python. I've been using this and it saves having to port single cell data back and forth between R and python, which is always nice.

I'd like to try to make this interoperable with scanpy and the rest of scverse. I've written some code to extract the relevant data from an anndata object and run slingshot on it, so that someone using scanpy can run pyslingshot with a single command (e.g., `sc.ex.tl.slingshot(adata)`) and then have the results incorporated into the adata object and easily plottable the same way results of any other analysis are. I'm using this already in my notebooks and it saves a lot of time and code to not have to do the conversion manually in every notebook.

However, before I can do a pull request to the scanpy repository, this package needs to be fully installable with pip/pypi, which it is currently not due to its dependency on a branch of pcurvepy that isn't on pypi. See this thread on stackexchange:

https://stackoverflow.com/a/45264657

Would you be willing to either add your pcurvepy branch to this repository as a submodule, or put it on pypi under a different name ("pcurvepy2"?) so that pyslingshot does not depend on a package that's not on pypi? This would both make it easier to install (just `pip install pyslingshot` instead of also needing the other command for pcurvepy) and easier to integrate with other tools.

If you need any help with this, let me know. And thank you for your time!

**Comment by mossjacob** [comment]
What is not currently done is adding the pseudotime back to the anndata, but this can be added easily

**Comment by mossjacob** [comment]
Hi @esrice , did the update fix this problem for you?

**Comment by esrice** [comment]
Hi @mossjacob, sorry, I haven't gotten around to doing that integration with scanpy yet, but based on your comment, that should definitely fix the problem I was having. Thanks! I'll let you know if/when I get to that how it goes.
