### ISSUE TITLE
How to use scRNAseq anndata with slingshot python package

### ISSUE THREAD

**Issue by ryanhchung** [mossjacob/pyslingshot#13]
Hi Team,

I was wondering how can I apply scRNAseq anndata to your package, as the tutorial is written with numpy object.

I tried to apply 

slingshot = Slingshot(adata, scanpy_clusters, start_node="SCP", debug_level='verbose') but the function cannot recognize the parameters.

Any tips or methods that I can apply my anndata?

Thanks!

**Comment by mossjacob** [comment]
See #12 and associated PR #14
