### ISSUE TITLE
how an obtein the pseudotime in a numpy variable 

### ISSUE THREAD

**Issue by CRISTIANJULIOCESAR** [mossjacob/pyslingshot#5]
I Would  like to have the pseudotime  and  the 2d coordinates  of this pseudotime but i can not extract them  in a numpy array or pandas dataframe.

Here is the code, i follow the tutorial, I dont want to use the functions in the tutorial to plot, i just need the pseudo time and the coordinates in numpy or pandas, in R seems to be more easy to get that:

https://colab.research.google.com/drive/11mjSTkeYbqOnFYUkA12wo5T-gHSCA2Of#scrollTo=Awkmx-ZaFjT0&uniqifier=1

But i can not do it in Python.

in R is just like this:
# Load data
data = read.csv(sprintf("%s/data.csv", out_dir), header=FALSE)
clusters = read.csv(sprintf("%s/clusters.csv", out_dir), header=FALSE)[, 1]
exprs = read.csv(sprintf("%s/exprs.csv", out_dir), row.names=1)

# Slingshot
print('Lineages...')
lin1 <- getLineages(data, clusters, start.clus = 0)
print('Curves...')
crv1 <- getCurves(lin1)
print('Pseudotime...')
pst <- slingPseudotime(crv1)
w <- slingCurveWeights(crv1)
L <- length(slingLineages(crv1))

There is something similar in Python?
Plz, Can you help me with that? thank you!

**Comment by mossjacob** [comment]
Hi, you can get the pseudotime from `curves` similarly as follows:
```
lin1 = 0
crv1 = slingshot.curves[lin1]
pst = crv1.pseudotimes_interp
```
